// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: relay.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayType int32

const (
	RelayType_NO_RELAY       RelayType = 0
	RelayType_HTTP_FORWARD   RelayType = 1
	RelayType_STREAM_FORWARD RelayType = 2
	RelayType_EVENT_FORWARD  RelayType = 3
	RelayType_SYSTEM         RelayType = 4
)

// Enum value maps for RelayType.
var (
	RelayType_name = map[int32]string{
		0: "NO_RELAY",
		1: "HTTP_FORWARD",
		2: "STREAM_FORWARD",
		3: "EVENT_FORWARD",
		4: "SYSTEM",
	}
	RelayType_value = map[string]int32{
		"NO_RELAY":       0,
		"HTTP_FORWARD":   1,
		"STREAM_FORWARD": 2,
		"EVENT_FORWARD":  3,
		"SYSTEM":         4,
	}
)

func (x RelayType) Enum() *RelayType {
	p := new(RelayType)
	*p = x
	return p
}

func (x RelayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayType) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[0].Descriptor()
}

func (RelayType) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[0]
}

func (x RelayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayType.Descriptor instead.
func (RelayType) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

type SystemEvent int32

const (
	SystemEvent_UNSPECIFIED   SystemEvent = 0
	SystemEvent_READY         SystemEvent = 1
	SystemEvent_HEALTH        SystemEvent = 2
	SystemEvent_MATCH_CREATED SystemEvent = 3
	SystemEvent_MATCH_ENDED   SystemEvent = 4
	SystemEvent_METRIC        SystemEvent = 5
)

// Enum value maps for SystemEvent.
var (
	SystemEvent_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "READY",
		2: "HEALTH",
		3: "MATCH_CREATED",
		4: "MATCH_ENDED",
		5: "METRIC",
	}
	SystemEvent_value = map[string]int32{
		"UNSPECIFIED":   0,
		"READY":         1,
		"HEALTH":        2,
		"MATCH_CREATED": 3,
		"MATCH_ENDED":   4,
		"METRIC":        5,
	}
)

func (x SystemEvent) Enum() *SystemEvent {
	p := new(SystemEvent)
	*p = x
	return p
}

func (x SystemEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[1].Descriptor()
}

func (SystemEvent) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[1]
}

func (x SystemEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemEvent.Descriptor instead.
func (SystemEvent) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

type RelayPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      RelayType      `protobuf:"varint,1,opt,name=type,proto3,enum=RELAY_PAYLOAD.RelayType" json:"type,omitempty"`
	Path      string         `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Key       string         `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Pkt       []byte         `protobuf:"bytes,4,opt,name=pkt,proto3" json:"pkt,omitempty"`
	SysMsg    *SystemMessage `protobuf:"bytes,5,opt,name=sys_msg,json=sysMsg,proto3" json:"sys_msg,omitempty"`
	Timestamp int64          `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *RelayPayload) Reset() {
	*x = RelayPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayPayload) ProtoMessage() {}

func (x *RelayPayload) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayPayload.ProtoReflect.Descriptor instead.
func (*RelayPayload) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RelayPayload) GetType() RelayType {
	if x != nil {
		return x.Type
	}
	return RelayType_NO_RELAY
}

func (x *RelayPayload) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RelayPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RelayPayload) GetPkt() []byte {
	if x != nil {
		return x.Pkt
	}
	return nil
}

func (x *RelayPayload) GetSysMsg() *SystemMessage {
	if x != nil {
		return x.SysMsg
	}
	return nil
}

func (x *RelayPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SystemMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event             SystemEvent `protobuf:"varint,1,opt,name=event,proto3,enum=RELAY_PAYLOAD.SystemEvent" json:"event,omitempty"`
	PlayerCountChange int32       `protobuf:"varint,2,opt,name=player_count_change,json=playerCountChange,proto3" json:"player_count_change,omitempty"`
	Gameserver        *GSMetric   `protobuf:"bytes,3,opt,name=gameserver,proto3" json:"gameserver,omitempty"`
}

func (x *SystemMessage) Reset() {
	*x = SystemMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage) ProtoMessage() {}

func (x *SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage.ProtoReflect.Descriptor instead.
func (*SystemMessage) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *SystemMessage) GetEvent() SystemEvent {
	if x != nil {
		return x.Event
	}
	return SystemEvent_UNSPECIFIED
}

func (x *SystemMessage) GetPlayerCountChange() int32 {
	if x != nil {
		return x.PlayerCountChange
	}
	return 0
}

func (x *SystemMessage) GetGameserver() *GSMetric {
	if x != nil {
		return x.Gameserver
	}
	return nil
}

type GSMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerCount int32 `protobuf:"varint,1,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	MatchCount  int32 `protobuf:"varint,2,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
}

func (x *GSMetric) Reset() {
	*x = GSMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GSMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSMetric) ProtoMessage() {}

func (x *GSMetric) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSMetric.ProtoReflect.Descriptor instead.
func (*GSMetric) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *GSMetric) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *GSMetric) GetMatchCount() int32 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

var File_relay_proto protoreflect.FileDescriptor

var file_relay_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x52,
	0x45, 0x4c, 0x41, 0x59, 0x5f, 0x50, 0x41, 0x59, 0x4c, 0x4f, 0x41, 0x44, 0x22, 0xc9, 0x01, 0x0a,
	0x0c, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2c, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x52, 0x45,
	0x4c, 0x41, 0x59, 0x5f, 0x50, 0x41, 0x59, 0x4c, 0x4f, 0x41, 0x44, 0x2e, 0x52, 0x65, 0x6c, 0x61,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6b, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x70, 0x6b, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x52, 0x45, 0x4c, 0x41, 0x59, 0x5f, 0x50, 0x41, 0x59,
	0x4c, 0x4f, 0x41, 0x44, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x06, 0x73, 0x79, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xaa, 0x01, 0x0a, 0x0d, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x52, 0x45, 0x4c, 0x41,
	0x59, 0x5f, 0x50, 0x41, 0x59, 0x4c, 0x4f, 0x41, 0x44, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0a,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x52, 0x45, 0x4c, 0x41, 0x59, 0x5f, 0x50, 0x41, 0x59, 0x4c, 0x4f, 0x41, 0x44,
	0x2e, 0x47, 0x53, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x08, 0x47, 0x53, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x5e, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x4c, 0x41, 0x59, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x46, 0x4f, 0x52, 0x57, 0x41, 0x52, 0x44,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x46, 0x4f, 0x52,
	0x57, 0x41, 0x52, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f,
	0x46, 0x4f, 0x52, 0x57, 0x41, 0x52, 0x44, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x53,
	0x54, 0x45, 0x4d, 0x10, 0x04, 0x2a, 0x65, 0x0a, 0x0b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x0f, 0x0a, 0x0b, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x04,
	0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x54, 0x52, 0x49, 0x43, 0x10, 0x05, 0x42, 0x29, 0x5a, 0x10,
	0x70, 0x62, 0x2f, 0x6d, 0x69, 0x74, 0x73, 0x75, 0x6b, 0x6f, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0xaa, 0x02, 0x14, 0x4d, 0x69, 0x74, 0x73, 0x75, 0x6b, 0x6f, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData = file_relay_proto_rawDesc
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(file_relay_proto_rawDescData)
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_relay_proto_goTypes = []interface{}{
	(RelayType)(0),        // 0: RELAY_PAYLOAD.RelayType
	(SystemEvent)(0),      // 1: RELAY_PAYLOAD.SystemEvent
	(*RelayPayload)(nil),  // 2: RELAY_PAYLOAD.RelayPayload
	(*SystemMessage)(nil), // 3: RELAY_PAYLOAD.SystemMessage
	(*GSMetric)(nil),      // 4: RELAY_PAYLOAD.GSMetric
}
var file_relay_proto_depIdxs = []int32{
	0, // 0: RELAY_PAYLOAD.RelayPayload.type:type_name -> RELAY_PAYLOAD.RelayType
	3, // 1: RELAY_PAYLOAD.RelayPayload.sys_msg:type_name -> RELAY_PAYLOAD.SystemMessage
	1, // 2: RELAY_PAYLOAD.SystemMessage.event:type_name -> RELAY_PAYLOAD.SystemEvent
	4, // 3: RELAY_PAYLOAD.SystemMessage.gameserver:type_name -> RELAY_PAYLOAD.GSMetric
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GSMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relay_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		EnumInfos:         file_relay_proto_enumTypes,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_rawDesc = nil
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
